resolver: lts-7.13
packages:
- '.'
- location:
    git: https://github.com/ndmitchell/bake.git
    commit: fa449f2a015a1dc56968cee77fa349eb50e3639d
extra-deps:
- bake-0.5.0
- extra-1.5.1
flags: {}
extra-package-dbs: []
docker:
  enable: true
